name: ServiceNow GitHub Actions Demo

on:
  pull_request:
    branches: [ $default-branch ]
  push:
    branches: [ master ]

jobs:
  build:
    name: Apply Remote Change and Publish
    runs-on: ubuntu-latest
    
    steps:

      - name: ServiceNow CI/CD Apply Changes
        uses: ServiceNow/sncicd-apply-changes@1.0.0
        env:
          snowUsername: ${{ secrets.SNOW_USERNAME }}
          snowPassword: ${{ secrets.SNOW_PASSWORD }}
          snowSourceInstance: ${{ secrets.SNOW_SOURCE_INSTANCE }}
          appSysID: ${{ secrets.APP_SYS_ID }}
          appScope: ${{ secrets.APP_SCOPE }}

      - name: ServiceNow CI/CD Publish App
        id: publish_app
        uses: ServiceNow/sncicd-publish-app@1.0.0
        with:
          devNotes: "string"
          versionFormat: detect
        env:
          snowUsername: ${{ secrets.SNOW_USERNAME }}
          snowPassword: ${{ secrets.SNOW_PASSWORD }}
          snowSourceInstance: ${{ secrets.SNOW_SOURCE_INSTANCE }}
          appSysID: ${{ secrets.APP_SYS_ID }}
          appScope: ${{ secrets.APP_SCOPE }}

jobs:
  test:
    name: Install and Run CI Build Tests
    runs-on: ubuntu-latest
    
    steps:

      - name: ServiceNow CI/CD Install App
        id: install_app
        uses: ServiceNow/sncicd-install-app@1.0.0
        with:
          version: ${{steps.publish_app.outputs.newVersion}}
        env:
          snowUsername: ${{ secrets.SNOW_USERNAME }}
          snowPassword: ${{ secrets.SNOW_PASSWORD }}
          snowInstallInstance: ${{ secrets.SNOW_INSTALL_INSTANCE }}
          appSysID: ${{ secrets.APP_SYS_ID }}
          appScope: ${{ secrets.APP_SCOPE }}

      - name: ServiceNow CI/CD Run ATF Test Suite
        uses: ServiceNow/sncicd-tests-run@1.0.0
        with:
          browserName:
          browserVersion:
          osName:
          osVersion:
          testSuiteSysId:
          testSuiteName:
        env:
          snowUsername: ${{ secrets.SNOW_USERNAME }}
          snowPassword: ${{ secrets.SNOW_PASSWORD }}
          snowInstallInstance: ${{ secrets.SNOW_INSTALL_INSTANCE }}

      - name: ServiceNow CI/CD Rollback App
        if: ${{ failure() && steps.install_app.outputs.rollbackVersion }}
        uses: ServiceNow/sncicd-rollback-app@1.0.0
        with:
          version: ${{steps.install_app.outputs.rollbackVersion}}
        env:
          snowUsername: ${{ secrets.SNOW_USERNAME }}
          snowPassword: ${{ secrets.SNOW_PASSWORD }}
          snowInstallInstance: ${{ secrets.SNOW_INSTALL_INSTANCE }}
          appSysID: ${{ secrets.APP_SYS_ID }}
          appScope: ${{ secrets.APP_SCOPE }}

jobs:
  deploy:
    name: Deploy on Merge to Master
    runs-on: ubuntu-latest
    
    steps:

      - name: ServiceNow CI/CD Install App
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        id: install_app
        uses: ServiceNow/sncicd-install-app@1.0.0
        with:
          version: ${{steps.publish_app.outputs.newVersion}}
        env:
          snowUsername: ${{ secrets.SNOW_USERNAME }}
          snowPassword: ${{ secrets.SNOW_PASSWORD }}
          snowInstallInstance: ${{ secrets.SNOW_INSTALL_INSTANCE }}
          appSysID: ${{ secrets.APP_SYS_ID }}
          appScope: ${{ secrets.APP_SCOPE }}
